version: "3.9"

services:
  apache:
    build: .
    container_name: lamp-apache
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html        # Persistent web files
      - ./apache-config:/etc/apache2/sites-enabled
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: lamp_db
    restart: always

  mysql:
    image: mysql:8.0
    container_name: lamp-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp_db
    volumes:
      - mysql-data:/var/lib/mysql    # Persistent MySQL data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    restart: always

volumes:
  mysql-data:
    driver: local
